# Access via "http://localhost:8080"
services:
  mediawiki:
    image: secu73020-wiki:latest
    restart: always
    volumes:
      - ./images:/var/www/html/images
      - ./data:/var/www/data
  nginx:
    image: nginx:1.29.3-alpine-slim
    restart: always
    links:
      - mediawiki
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
